name: Hussfelt
author: Henrik Hussfelt
markdown: redcarpet
pygments: true
baseurl: 
description: Head of Mobile, Linas Matkasse
github: https://github.com/hussfelt
twitter: https://twitter.com/hussfelt
facebook: https://facebook.com/hussfelt
linkedin: https://se.linkedin.com/in/henrikhussfelt/
email: henrik.hussfelt@gmail.com
location: 59.342262, 18.112334
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

