title:        '@hussfelt'
tagline:      'Home of @hussfelt'
description:  'Head of Mobile at @LinasMatkasse. Technical startup advisor with a passion for doing the right thing.'
url:          http://hussfelt.net
version:      1.1.1
author:
  name:       'Henrik'
  email:      'henrik@henrik.se'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
